DO $$
DECLARE
    n INT := 50000;
    t_start TIMESTAMP;
    t_end   TIMESTAMP;
    t_no_trg INTERVAL;
    t_with_trg INTERVAL;
    slowdown_pct NUMERIC;
BEGIN
    RAISE NOTICE '=== Нагрузочный тест репликации (N=% строк) ===', n;
    ALTER TABLE replication.work_table DISABLE TRIGGER ALL;
    EXECUTE 'TRUNCATE TABLE replication.work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.repl_work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.replication_queue RESTART IDENTITY';
    t_start := clock_timestamp();
    INSERT INTO replication.work_table (int_field, text_field) SELECT i, 'val_' || i FROM generate_series(1, n) AS i;
    t_end := clock_timestamp();
    t_no_trg := t_end - t_start;
    ALTER TABLE replication.work_table ENABLE TRIGGER ALL;
    EXECUTE 'TRUNCATE TABLE replication.work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.repl_work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.replication_queue RESTART IDENTITY';
    t_start := clock_timestamp();
    INSERT INTO replication.work_table (int_field, text_field) SELECT i, 'val_' || i FROM generate_series(1, n) AS i;
    t_end := clock_timestamp();
    t_with_trg := t_end - t_start;
    slowdown_pct := (EXTRACT(EPOCH FROM t_with_trg) / NULLIF(EXTRACT(EPOCH FROM t_no_trg), 0) - 1) * 100;
    RAISE NOTICE 'INSERT: Без триггеров [%], С триггерами [%]. Замедление: %.2f%%', t_no_trg, t_with_trg, slowdown_pct;
    ALTER TABLE replication.work_table DISABLE TRIGGER ALL;
    EXECUTE 'TRUNCATE TABLE replication.work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.repl_work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.replication_queue RESTART IDENTITY';
    INSERT INTO replication.work_table (int_field, text_field) SELECT i, 'val_' || i FROM generate_series(1, n) AS i;
    t_start := clock_timestamp();
    UPDATE replication.work_table SET int_field = 0;
    t_end := clock_timestamp();
    t_no_trg := t_end - t_start;
    ALTER TABLE replication.work_table ENABLE TRIGGER ALL;
    EXECUTE 'TRUNCATE TABLE replication.work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.repl_work_table RESTART IDENTITY';
    EXECUTE 'TRUNCATE TABLE replication.replication_queue RESTART IDENTITY';
    INSERT INTO replication.work_table (int_field, text_field) SELECT i, 'val_' || i FROM generate_series(1, n) AS i;
    t_start := clock_timestamp();
    UPDATE replication.work_table SET int_field = 0;
    t_end := clock_timestamp();
    t_with_trg := t_end - t_start;
    slowdown_pct := (EXTRACT(EPOCH FROM t_with_trg) / NULLIF(EXTRACT(EPOCH FROM t_no_trg), 0) - 1) * 100;
    RAISE NOTICE 'UPDATE: Без триггеров [%], С триггерами [%]. Замедление: %.2f%%', t_no_trg, t_with_trg, slowdown_pct;
    RAISE NOTICE '=== Тест завершен ===';
END $$;